### ISSUE TITLE
Create a new AuthorityResolver for EVERYONE group

### ISSUE THREAD

**Issue by douglascrp** [Conexiam/alfresco-acl-templates#15]
It would be useful to have a ready to use "EveryoneGroupAuthorityResolver".

**Comment by jpotts** [comment]
I am not sure why this is needed. Your ACL template can contain static entries--you do not have to use authority templates. So, for example, you could have a completely static ACL template and it could include the EVERYONE group, like this:

```
{
  "inherit": false,
  "permissions": [
    {
      "authority": ”GROUP_EVERYONE",
      "permission": "Collaborator”
    },
    {
      "authority": ”GROUP_Client A Team",
      "permission": "Collaborator”
    }
  ]
}
```

This is the same thing as using an authority template resolver that just returns a hardcoded string.

**Comment by jpotts** [comment]
Also, sorry it took so long to reply.
